### ISSUE TITLE
RFE: Make fedocal vacations visible in pkgdb

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/pkgdb2#199]
It'd be nice if someone looking at a user in pkgdb could see if that user is (or was recently) on vacation.

This should include the points of contact and maintainers in the package view — maybe an on vacation icon, color, or other marker.

**Comment by ralphbean** [comment]
Nice idea!  To add a little more, how about we make fedocal provide:

- an API endpoint where you can provide a username and it will tell you if that person is on vacation or not.
- a dynamically generated .png file for every user that indicates whether or not the user is on vacation at any given time.

We could pepper these indicators all throughout our other apps.

**Comment by pypingou** [comment]
So I made the fedocal API flexible enough that we can use any calendar (just have to specify which) and it will return a small shield, relying on http://buckler.repl.ca/ if the user is in a meeting in the specified calendar, otherwise it returns nothing.

Example shield: ![http://b.repl.ca/v1/mattdm-in_vacation-brightgreen.png](http://b.repl.ca/v1/mattdm-in_vacation-brightgreen.png)
