### ISSUE TITLE
Packages with no (bugzilla) watchers in pkgdb don't get synced on a branch

### ISSUE THREAD

**Issue by TC01** [fedora-infra/pkgdb2#323]
This happened [to librsvg2](https://fedorahosted.org/rel-eng/ticket/6356#comment:1) and also [media-player-info](https://admin.fedoraproject.org/pkgdb/package/rpms/media-player-info/) after the F24 branch, but there are almost certainly more of these packages. 

Because the bugzilla sync fails, the packages don't get imported to Rawhide.

**Comment by pypingou** [comment]
This should have been fixed by: https://github.com/fedora-infra/pkgdb2/pull/240/ but looking at the timeline https://admin.fedoraproject.org/pkgdb/package/rpms/media-player-info/timeline it seems it has a bug :-/

**Comment by pypingou** [comment]
Cc'ing @nirik 

Geez that took me a while but in fact it is working correctly, the "bug" was fixed in october 2015 and the timeline indicates february 2015 (and not 2016!).

So this makes sense.

I have a script running to find all the active packages where no-one has watchbugzilla, once we fixed those we should be set.

**Comment by pypingou** [comment]
I forgot to update this ticket but the script ran and all the packages I could find in this situation have been fixed.

So this should be fixed and we should be good for the next branching :)
